- name: Get secrets
  hosts: localhost
  become: true
  tasks:
    - name: Install hvac
      ansible.builtin.pip:
        name: hvac
        state: present
        executable: pip3.11

    - name: Create file with vault secrets
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/common token=AES:27DI0XfekZp8epZoWyANtw==:yQe3sMdbuPiKYIUYlxzNbwpmfNOTh46VjrbwSOw8Gxg= url=https://vault-internal.dkdevops.online:8200 validate_certs=False')}}"
        create: yes

    - name: Create file with vault secrets
      ansible.builtin.lineinfile:
        path: ~/app.json
        line: "{{ lookup('hashi_vault', 'secret=app/data/expense token=AES:27DI0XfekZp8epZoWyANtw==:yQe3sMdbuPiKYIUYlxzNbwpmfNOTh46VjrbwSOw8Gxg= url=https://vault-internal.dkdevops.online:8200 validate_certs=False')}}"
        create: yes