- name: Get secrets
  hosts: localhost
  vars:
    secrets: {}
  tasks:
    - name: Install hvac
      ansible.builtin.pip:
        name: hvac
        state: present
        executable: pip3.11

    - name: Create file with vault secrets
      ansible.builtin.set_fact:
        secrets: "{{ secrets | combine(lookup('hashi_vault', 'secret=' + item + ' token=' + vault_token + ' url=https://vault-internal.dkdevops.online:8200 validate_certs=False')) }}"

      loop:
        - common/data/common
        - common/data/newrelic
        - rds/data/{{ env }}

    - name: Write secrets to a JSON file
      ansible.builtin.copy:
        content: "{{ secrets | to_json }}"
        dest: ~/secrets.json


#    - name: Create Secrets Files
#        ansible.builtin.lineinfile:
#          path: ~/{{item |split("/") |last}}.json
#          line: "{{lookup('hashi_vault', 'secret={{item}} token={{vault_token}} url=https://vault.rdevops6a.online:8200 validate_certs=False')}}"
#          create: yes
#        loop:
#          - "common/data/common"
#          - "expense-{{env}}/data/{{role_name}}"
#          - "rds/data/{{env}}"
#
#          - name: Create Common Secret
#            ansible.builtin.shell: for i in $(ls ~/*.json); do echo -n $(cat $i) ;done | sed -e 's/}{/, /g' >~/secrets.json