- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Import app pre-req
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Copy configuration file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import tasks from newrelic
  ansible.builtin.import_role:
    name: newrelic
    tasks_from: nginx

- name: start nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true
