- name: mysql database
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: Install bottle for Python 3.3 specifically, using the 'pip3.3' executable
  ansible.builtin.pip:
    name:
      - PyMySQL
      - cryptography
    executable: pip



- name: Mysql password setup
  ansible.builtin.shell:  mysql_secure_installation --set-root-pass ExpenseApp@1
