format_version: 10
pipelines:
  backend:
    group: expense-ansible
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    secure_variables:
      vault_token: "AES:lkylhsuIQR2lugI2qkBUAQ==:whu9V0XLTc7w2MpuA+ls9oYZQrW61Gqr/IWWyF2uYzg="
    stages:
    - dev:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          backend:
            timeout: 0
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - backend
                command: bash
                run_if: passed
    - qa:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - ansible.sh
                    - backend
                  command: bash
                  run_if: passed
    - stage:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - ansible.sh
                    - backend
                  command: bash
                  run_if: passed
    - prod:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - ansible.sh
                    - backend
                  command: bash
                  run_if: passed

