format_version: 10
pipelines:
  backend:
    group: expense-ansible
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    secure_variables:
      vault_token: AES:KTyB14NEWwAxxYn1GfEfeg==:L4q2mauJj1U1+BXf/oY8jkzf4o61ZlQTrPkBkylR51I=
    stages:
    - dev:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          backend:
            timeout: 0
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - backend
                command: bash
                run_if: passed


