format_version: 10
pipelines:
  Frontend:
    group: defaultGroup
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    stages:
    - dev:
        fetch_materials: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -i
                - frontend-dev.dkdevops.online,
                - -e
                - ansible_user=ec2-user
                - -e
                - ansible_password=DevOps321
                - frontend.yml
                command: ansible-playbook
                run_if: passed
    - qa:
        fetch_materials: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -i
                    - frontend-qa.dkdevops.online,
                    - -e
                    - ansible_user=ec2-user
                    - -e
                    - ansible_password=DevOps321
                    - frontend.yml
                  command: ansible-playbook
                  run_if: passed
    - stage:
        fetch_materials: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -i
                    - frontend-stage.dkdevops.online,
                    - -e
                    - ansible_user=ec2-user
                    - -e
                    - ansible_password=DevOps321
                    - frontend.yml
                  command: ansible-playbook
                  run_if: passed
    - prod:
        fetch_materials: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - -i
                    - frontend-prod.dkdevops.online,
                    - -e
                    - ansible_user=ec2-user
                    - -e
                    - ansible_password=DevOps321
                    - frontend.yml
                  command: ansible-playbook
                  run_if: passed

