format_version: 10
pipelines:
  Frontend:
    group: expense-ansible
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    environment_variables:
      env: dev
    secure_variables:
      vault_token: AES:KjNW8iXptaW+i8jH2rZ6yg==:Tj+j15Thnd8aioQD6Ecu6trMWY8eGltB+o96M+tF7t8=
    stages:
    - dev:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - frontend
                command: bash
                run_if: passed

