format_version: 10
pipelines:
  mysql:
    group: expense-ansible
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    secure_variables:
      vault_token: AES:27DI0XfekZp8epZoWyANtw==:yQe3sMdbuPiKYIUYlxzNbwpmfNOTh46VjrbwSOw8Gxg=
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - -i
                      - mysql-dev.dkdevops.online,
                      - -e
                      - "@secrets.json"
                      - expense.yml
                      - -e
                      - role_name=mysql
                    command: ansible-playbook #bash ansible.sh mysql
                    run_if: passed


