format_version: 10
pipelines:
  mysql:
    group: expense-ansible
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    secure_variables:
      vault_token: AES:27DI0XfekZp8epZoWyANtw==:yQe3sMdbuPiKYIUYlxzNbwpmfNOTh46VjrbwSOw8Gxg=
    stages:
    - dev:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                  - ansible.sh
                  - mysql
                command: bash
                run_if: passed
    - qa:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - ansible.sh
                    - mysql
                  command: bash
                  run_if: passed
    - stage:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - ansible.sh
                    - mysql
                  command: bash
                  run_if: passed
    - prod:
        fetch_materials: true
        approval:
          type: manual
        jobs:
          Test:
            timeout: 0
            tasks:
              - exec:
                  arguments:
                    - ansible.sh
                    - mysql
                  command: bash
                  run_if: passed

