format_version: 10
pipelines:
  mysql:
    group: expense-ansible
    materials:
      git-4210a58:
        git: https://github.com/Devops-Stage-1/expense-ansible.git
        shallow_clone: false
        branch: main
    secure_variables:
      vault_token: AES:KTyB14NEWwAxxYn1GfEfeg==:L4q2mauJj1U1+BXf/oY8jkzf4o61ZlQTrPkBkylR51I=
    stages:
      - DEV:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      #- -i
                      #- mysql-dev.dkdevops.online,
                      #- -e
                      #- "@secrets.json"
                      #- expense.yml
                      #- -e
                      #- role_name=mysql
                      - ansible.sh
                      - mysql
                    #command: ansible-playbook #bash ansible.sh mysql
                    command: bash
                    run_if: passed


