- name: Set-prompt
  ansible.builtin.shell: set-prompt {{ component }}

- name: Install Node_exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter
  when: node_exporter_needed
- name: Import tasks from logstash
  ansible.builtin.import_role:
    name: logstash
    tasks_from: main
  when: logstash_configuration_needed